# Generated by Django 4.0.4 on 2022-06-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeAPI', '0003_orderitem_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='category',
            field=models.CharField(choices=[('C', 'Shirt'), ('A', 'Accessories'), ('L', 'Life Style')], default='L', max_length=1),
        ),
    ]
