# Generated by Django 4.0.4 on 2022-06-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeAPI', '0008_order_shippingaddress_review_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
