# Generated by Django 4.0.4 on 2022-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeAPI', '0005_address_user_order_user_alter_storeitems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
